name: Build and publish Docs

on: workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Doxygen
      run: |
        sudo apt-add-repository universe
        sudo apt-get update
        sudo apt-get install -y doxygen
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build Docs
      run: cmake --build ${{github.workspace}}/build docs

    - name: Upload to Github Pagwes
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: ${{github.workspace}}/build/docs
          

    


